### ISSUE TITLE
panic: unclosed section on certain ".cmd" files

### ISSUE THREAD

**Issue by smiglo5** [SuperFromND/iguana#12]
Hey there!
Is it possible to ignore that error when it comes to "broken" .cmd file that gives this error?

![cmd_7ZGmPiWq4I](https://github.com/user-attachments/assets/20858198-6f01-4ce9-911f-c6f494b11a38)

For now, this script just shuts down after it encounters that error, would be nice if it just ignores that one, and do the rest of them.

I'm using `iguana.exe -i path/to/folder` method

**Comment by SuperFromND** [comment]
I can't do much to help characters that have straight-up-invalid INI syntax (the library Iguana uses for parsing requires it), sorry! Your best bet would just be to edit that particular file and fix the broken section(s?).
